[build]
  # Build command for deployment
  command = "cd frontend && npm install && npm run build"
  # Output directory (relative to project root)
  publish = "frontend/dist"
  # Functions directory
  functions = "netlify/functions"

[dev]
  # Local dev server port
  port = 8888
  # Frontend framework detection (auto-starts vite)
  framework = "#custom"
  # Custom command to run frontend dev server
  command = "cd frontend && npm run dev"
  # Where frontend dev server runs
  targetPort = 5173
  # Auto-open browser (BeeSwarm handles this)
  autoLaunch = false

# Redirect all unknown routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
