[build]
  # Build command for deployment
  command = "cd frontend && npm install && npm run build"
  # Output directory (relative to project root)
  publish = "frontend/dist"
  # Functions directory
  functions = "netlify/functions"

[dev]
  # BeeSwarm automatically allocates unique ports for each project
  # Base port 8888 - will be updated to 8888, 8889, 8890, etc.
  port = 8888
  # Frontend framework detection
  framework = "#custom"
  # IMPORTANT: Use npm --prefix instead of cd to keep process running
  command = "npm --prefix frontend run dev"
  # BeeSwarm automatically updates this to match allocated Vite port (5174, 5175, 5176, etc.)
  targetPort = 5174
  # Auto-open browser (BeeSwarm handles this)
  autoLaunch = false

# Redirect all unknown routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
