[build]
  base = "/"
  publish = "frontend/build"
  command = "npm install && cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 