[build]
  # Build command for deployment
  command = "cd frontend && npm install && npm run build"
  # Output directory (relative to project root)
  publish = "frontend/dist"
  # Functions directory
  functions = "netlify/functions"

[dev]
  # Local dev server port (BeeSwarm allocates ports 8888-8999 automatically)
  # Port conflicts are handled with auto-retry
  port = 8888
  # Frontend framework detection
  framework = "#custom"
  # IMPORTANT: Use npm --prefix instead of cd to keep process running
  command = "npm --prefix frontend run dev"
  # Where frontend dev server runs (5174 to avoid conflict with BeeSwarm's port 5173)
  targetPort = 5174
  # Auto-open browser (BeeSwarm handles this)
  autoLaunch = false

# Redirect all unknown routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
